### PR TITLE
Iterate through digits directly in Julia munchausen implementation

### PR DESCRIPTION
**Pull request by brenhinkeller**
Iterating through the digits directly using division and modulus (using code borrowed from your existing C implementation) speeds up the Julia munchausen number code by about a factor of eight

### CODE REVIEW

**Comment by brenhinkeller** [comment]
Nothing too important, but I think it illustrates a noteworthy property of Julia that the naive "just write like you would in C" approach tends to be fast

**Comment by ViralBShah** [comment]
Would be nice to merge this before the next round of benchmarks.

**Comment by JulesKouatchou** [comment]
Sorry, it is only now that I saw the pull request. Thank you for your contribution.

**Comment by brenhinkeller** [comment]
Thanks!

**Comment by ViralBShah** [comment]
Please do see the discussion in #7 too.

**Pull request merged**
